### ISSUE TITLE
Invalid error code used for riack_send_message and need to check get_resp

### ISSUE THREAD

**Issue by michael-downey** [trifork/riack#10]
riack_send_message is defined as returning an uint32_t but it has a return -1 on error.  Changing this to return 0 fixes the issue but since this is one of the few functions that is uint32_t instead of int I wasn't sure whether it would be better to convert it to return int instead.

Also in riack_get there is a missing check for whether the get_resp is valid.  If the rpb_get_resp__unpack fails then the code will dereference an invalid pointer.

**Comment by bachpedersen** [comment]
Thanks
Looks like don't check unpack result in general.
I will look into it and and make a fix.

**Comment by bachpedersen** [comment]
Should be fixed now

**Comment by michael-downey** [comment]
I looked through the changes and there needs to be changes to the checks on the riack_send_message calls.  Right now they all do something like "if (riack_send_message())" which will still be incorrect as -1 will be seen as success in that case not failure.

Otherwise the changes look good.  Thank you.

**Comment by bachpedersen** [comment]
What a blunder on my part.
Thanks again :+1:

**Comment by michael-downey** [comment]
Changes look good.  Thanks for the speedy fix.
