### ISSUE TITLE
Windows build failes, missing protoc

### ISSUE THREAD

**Issue by damian123** [trifork/riack#9]
I am getting this error when I try to compile the code because I am missing protocol buffers. I have protoc on my PC but how do I tell riack to use it?

> cmake src
> CMake Error at e:/dev/3rdparty/cmake/cmake-2.8.10.2-win32-x86/share/cmake-2.8/Mo
> dules/FindPackageHandleStandardArgs.cmake:97 (message):
>   Could NOT find ProtoBufC (missing: PROTOBUFC_INCLUDE_DIR
>   PROTOBUFC_LIBRARIES)
> Call Stack (most recent call first):
>   e:/dev/3rdparty/cmake/cmake-2.8.10.2-win32-x86/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:291 (_FPHSA_FAILURE_MESSAGE)
>   cmake/Modules/FindProtoBufC.cmake:46 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:13 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by bachpedersen** [comment]
Hi
On windows you need to tell cmake where to find the libraries you can do that in src\cmake\Modules\FindProtoBufC.cmake lines 19 & 20, or pass it as build options to cmake (but i dont remember the syntax for that)
